<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<h1>Service Temporarily Unavailable</h1>
<p>
    The server is temporarily unable to service your request due to maintenance downtime or capacity problems.
    Please try again later.
</p>
<p><strong>Email: </strong><a href="mailto:#">support@example.com</a></p>

<p><strong>Phone: </strong><a href="tel:#"> (555) 555-1234</a></p>

<h2>We’ll be back online shortly!</h2>