;zend_extension=/usr/lib/php82/modules/xdebug.so
xdebug.mode=develop,debug
xdebug.client_host=host.docker.internal
xdebug.max_nesting_level = 300
xdebug.client_port = 9007
xdebug.start_with_request = yes
xdebug.discover_client_host = 1
xdebug.show_error_trace = 1
xdebug.force_error_reporting = 1
xdebug.force_display_errors = 1
